language: python
matrix:
  include:
  - python: "2.7"
    env: TOXENV=py27
  - python: "3.3"
    env: TOXENV=py33
  - python: "3.4"
    env: TOXENV=py34
  - python: "3.5"
    env: TOXENV=py35
  - python: "3.6"
    env: TOXENV=py36
  - python: "2.7"
    env: TOXENV=pep8py2
  - python: "3.6"
    env: TOXENV=pep8py3
install:
  - pip install --upgrade pip setuptools wheel tox
script:
  - tox
  - python setup.py packages
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - peter@pakos.uk
