branches:
  except:
  - python
language: bash
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

script:
- shellcheck ipa_check_consistency
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - peter@pakos.uk
